name: CI - Staging

on:
  pull_request:
    branches: [ staging ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout Code
        uses: actions/checkout@v4

      - name: Step 2 - Mock Lint & Validate Syntax
        run: echo "Validation Checks Passed Successfully."

      - name: Step 3 - Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Step 4, 5 & 6 - Build and Push Staging Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pakvista:staging-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pakvista:staging-${{ github.sha }}